Lanzamiento versión 0.1.0
IslasGECI/descarga_datos pull request #10
Opened 2020-04-07 17:52 UTC by evaristor

2020-04-27 19:41 UTC, evaristor commented
@nepito @islasfernando : Evoqué a los mutantes de este repo. En total hay 46 mutantes en este repo de los cuales ya cazamos 20. Faltan 26 mutantes por cazar. ¿Me podrían echar la mano?

2020-05-27 17:58 UTC, evaristor commented
Había algo incorrecto en la configuració anterior: se estaban mutando las pruebas (además del código). Corregí lo anterios moviendo el directorio de pruebas a la raíz. Ahora tenemos 33 mutantes en total, de los cuales ya cazamos 9. Quedan 24 mutantes sobrevivientes.

> 33:  🎉 9  🙁 24

2020-06-08 18:53 UTC, nepito commented
> Había algo incorrecto en la configuració anterior: se estaban mutando las pruebas (además del código). Corregí lo anterios moviendo el directorio de pruebas a la raíz. Ahora tenemos 33 mutantes en total, de los cuales ya cazamos 9. Quedan 24 mutantes sobrevivientes.
> 
> > 33:  tada 9  slightly_frowning_face 24

Ahí la llevamos 
> 32:  tada 11  slightly_frowning_face 21

2020-07-15 22:28 UTC, nepito requested changes
Hola @evaristor pareciera que está en el renglón de pruebas, pero "tradicionalmente" primero hacemos implementación. Por favor agrega el _checklist_ del renglón de [implementación](https://github.com/IslasGECI/manual#implementaci%C3%B3n-en-python).

2020-08-24 17:13 UTC, evaristor commented
![image](https://user-images.githubusercontent.com/3461018/91075146-766e2e00-e5f2-11ea-92e1-6bde1676a9fb.png)

2020-08-24 18:42 UTC, evaristor commented
Gracias @nepito  por orear este PR

2020-09-11 16:52 UTC, evaristor commented
![image](https://user-images.githubusercontent.com/3461018/92952202-748ad400-f414-11ea-8c7a-b0070cebf9b3.png)

2020-09-24 20:18 UTC, evaristor commented
Sobreviven 9 :space_invader:

![image](https://user-images.githubusercontent.com/3461018/94195838-643d1500-fe68-11ea-9826-a19b5217571a.png)

2020-11-05 22:53 UTC, xwalls commented
Será un placer ayudar en este PR
Abro Issue ✌

2020-11-10 23:02 UTC, xwalls commented
@nepito 
se han logrado dar caza a los mutantes restantes, mando revision ✌
![image](https://user-images.githubusercontent.com/9456708/98743813-e37d9e00-236d-11eb-813b-ea17d5b186e9.png)

2020-11-10 23:03 UTC, nepito commented
> @nepito
> se han logrado dar caza a los mutantes restantes, mando revision 
> ![image](https://user-images.githubusercontent.com/9456708/98743813-e37d9e00-236d-11eb-813b-ea17d5b186e9.png)

¡Dite-moi pas que c'est pas vrai! Muchas felicidades @xwalls . Justo hoy estábamos hablando de eso @MaritzaB y yo.

2020-11-11 23:24 UTC, nepito approved these changes
¡Listo @xwalls! Quedó a todo dar todo :raised_hands:

2020-11-11 23:26 UTC, merged