Feature/clase analysis
IslasGECI/descarga_datos pull request #4
Opened 2019-05-27 23:12 UTC by efren-cabrera

Agrega primer versión de clases Analysis y DataFile, aquí tomé la decisión de agregar un submódulo de pruebas para poder correrlas más facilmente

2019-05-28 18:39 UTC, efren-cabrera reviewed
Tal vez podríamos quitar docker del nombre del parámetro

2019-05-28 18:39 UTC, efren-cabrera commented on descarga_datos/internals/Analysis.py
> +    def __init__(self, name: str, description: str, docker_parent_image: str,
```suggestion
    def __init__(self, name: str, description: str, parent_image: str,
```

2019-05-28 18:39 UTC, efren-cabrera commented on descarga_datos/internals/Analysis.py
> +        self._docker_parent_image = docker_parent_image
```suggestion
        self._docker_parent_image = parent_image
```

2019-05-29 23:33 UTC, devarops reviewed
¿Está en el renglón de implementación, verdad?
¿Entonces no debo revisar documentación ni pruebas todavía?
¿Cómo verifico su funcionalidad?
¿Podrías hacer un _pull request_ más pequeño? (Creo que 9 consignaciones son demasiadas para un _pull request_)

2019-05-29 23:47 UTC, evaristor commented
@efren-cabrera
Podrías por favor indicarme en la descripción de este _pull request_ cómo correr las pruebas?

2019-05-30 00:44 UTC, efren-cabrera commented
> Podrías por favor indicarme en la descripción de este _pull request_ cómo correr las pruebas?

@evaristor para correr las pruebas puedes hacer `make tests`, tal vez sería conveniente revisarlo en un :tomato:

2019-05-31 07:51 UTC, evaristor commented
@efren-cabrera
¿A que hora prefieres el 🍅: a la 1 PM o a las 4 pm?

On Wed, May 29, 2019 at 5:44 PM Jesus Efren Cabrera Ortega <
notifications@github.com> wrote:

> Podrías por favor indicarme en la descripción de este *pull request* cómo
> correr las pruebas?
>
> @evaristor <https://github.com/evaristor> para correr las pruebas puedes
> hacer make tests, tal vez sería conveniente revisarlo en un 🍅
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/IslasGECI/descarga_datos/pull/4?email_source=notifications&email_token=AA2M7GTITAZNM2JKJF67DILPX4PORA5CNFSM4HP6W4GKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWRAUSQ#issuecomment-497158730>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AA2M7GWST4K6OC24AEIKZCLPX4PORANCNFSM4HP6W4GA>
> .
>

2019-06-03 18:48 UTC, devarops requested changes
Aquí van mi primer tanda de comentarios

2019-06-03 18:48 UTC, evaristor commented on descarga_datos/internals/Analysis.py
> +    def depends_on_file(self, filename: str) -> bool:
Tal vez conviene particularizar el nombre para indicar que verifica la dependencia en un archivo de datos específicamente (no lo hace, por ejemplo, en _scripts_). Tal vez algo como `depends_on_datafile` sería más apropiado?

2019-06-03 18:48 UTC, evaristor commented on Makefile
> +	docker run -it -e BITBUCKET_USERNAME=${BITBUCKET_USERNAME} -e BITBUCKET_PASSWORD=${BITBUCKET_PASSWORD} $(nombreRepositorio) bash -c "pip install . && $(foreach script, $(pruebasModulo), python -m $(
Por lo general prefiero la versión larga de las opciones. Por ejemplo `--help` en lugar de `-h`

2019-06-03 18:48 UTC, evaristor commented on descarga_datos/tests/test_Analysis.py
> +    def test_get_utl_to_file(self):
¿Hay aquí un _typo_?

```suggestion
    def test_get_url_to_file(self):
```

2019-06-03 18:48 UTC, evaristor commented on descarga_datos/internals/Analysis.py
> +    def depends_on_file(self, filename: str) -> bool:
Según nuestra guía, el nombre de las funciones que regresan un valor lógico debe empezar con _is_. ¿Es eso valido en este caso?

2019-06-05 23:09 UTC, efren-cabrera commented on Makefile
> +	docker run -it -e BITBUCKET_USERNAME=${BITBUCKET_USERNAME} -e BITBUCKET_PASSWORD=${BITBUCKET_PASSWORD} $(nombreRepositorio) bash -c "pip install . && $(foreach script, $(pruebasModulo), python -m $(
Las opciones de python no tienen versión larga

2019-06-06 00:02 UTC, devarops requested changes
Creo que este _pull request_ incluye más cosas que sólo la clase Analysis

2019-06-06 00:02 UTC, devarops commented on descarga_datos/internals/Analysis.py
> +    def is_dependant_on_datafile(self, filename: str) -> bool:
[Dependant vs. dependent](https://grammarist.com/spelling/dependant-dependent/)

> In American English, dependent is (1) an adjective meaning contingent on another, and (2) a noun meaning a person who is financially supported by someone else. Dependant is a rare alternative spelling with no definitions of its own.
> According to every British reference resource we checked, British English treats dependant as the noun and dependent as the adjective.

2019-06-06 00:02 UTC, devarops commented on Makefile
> +	start "" /max "README.pdf"
Creo que esto solo funciona en Windows y lo podríamos considerar ahora obsoleto, no?
(¿Tal vez este archivo no debería ser parte del _pull request_?)

2019-06-06 00:02 UTC, devarops commented on descarga_datos/__init__.py
> +from .internals import *
Si no importa el orden, podríamos ponerlo en orden alfabético?

2019-06-06 00:02 UTC, devarops commented on descarga_datos/internals/Analysis.py
> +    `get_url_to_file(filename: str, user: str): str`
Por consistencia no convendría llamarla `get_url_to_datafile`?

2019-06-06 00:02 UTC, devarops commented on descarga_datos/internals/Analysis.py
> +        >>> analisis.depends_on_datafile('archivo_ejemplo.csv')
Este nombre está desactualizado. Eso me hace sospechar que los ejemplos no corren? No se puede probar con _doctests_?

2019-06-06 00:02 UTC, evaristor commented on descarga_datos/tests/test_Analysis.py
> +import json
Si no importa el orden, podríamos ponerlo en orden alfabético?

2019-06-07 00:48 UTC, devarops requested changes

2019-06-07 00:48 UTC, evaristor commented on Makefile
> +tests:
¿El único propósito del `Makefile` es correr las pruebas? Tal vez conviene usar Travis?

2019-06-07 00:48 UTC, evaristor commented on descarga_datos/tests/test_Analysis.py
> +    def test_datafile_name(self):
¿Se pueden correr con Travis?

2019-06-07 00:48 UTC, evaristor commented on descarga_datos/internals/DataFile.py
> +    def __init__(self, source: str, path: str, filename: str, version: str, type: str):
No veo `type` en la documentación

2019-06-07 00:59 UTC, efren-cabrera commented
@evaristor ¿qué te parece si lo de travis lo dejamos para el renglón de pruebas? para que ya avance esta tarea, ya atendí tus otras correcciones ¿tu las revisas?

2019-06-10 22:38 UTC, devarops requested changes

2019-06-10 22:38 UTC, evaristor commented on descarga_datos/tests/test_Analysis.py
> +TEXTO_ANALYSIS = """[
Por favor podríamos verificar que `TEXTO_ANALYSIS` cumple con `analyses-schema.json`? Lo podemos hacer en un :tomato: si así lo prefieres

2019-06-10 23:18 UTC, devarops requested changes

2019-06-10 23:18 UTC, evaristor commented on Dockerfile
> +WORKDIR /workdir
Los `Dockerfile`s son típicamente de una línea.  Esta línea en particular no se requiera ya que la _parent image_ ya la incluye

2019-06-10 23:31 UTC, evaristor commented
> @evaristor ¿qué te parece si lo de travis lo dejamos para el renglón de pruebas? para que ya avance esta tarea, ya atendí tus otras correcciones ¿tu las revisas?

Me parece buena idea. Moví el _post-it_ de la clase Analysis a **aprobado**.

2019-06-18 00:03 UTC, closed without merging